// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9c76b466898c24476f4c6006cf99df14)
declare namespace Cloudflare {
  interface Env {
    GITHUB_CACHE: KVNamespace
    GITHUB_TOKEN: string
    ENVIRONMENT: string
    LOGFIRE_TOKEN: string
  }
}
interface Env extends Cloudflare.Env {}
