// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f138e50583bd93fd8851280f620972ab)
declare namespace Cloudflare {
  interface Env {
    GITHUB_CACHE: KVNamespace
    GITHUB_TOKEN: string
  }
}
interface Env extends Cloudflare.Env {}
